//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebActualizacionDatos.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiTabla
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Detalle { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Precio { get; set; }
        public int Cantidad { get; set; }
    }
}
